pipeline {
    agent any
    environment {
        TC_ARM64='/opt/toolchain/arm64-tc/bin'
        TC_ARM='/opt/toolchain/arm-tc/bin'
        CROSS_COMPILE_ta_arm64='aarch64-linux-gnu-'
        CROSS_COMPILE_ta_arm32='arm-linux-gnueabihf-'
        UEFI_TOOLS_DIR="${WORKSPACE}/uefi-tools"
        JENKINS_WORKSPACE="${WORKSPACE}"
   }

    stages {
        stage('Git checkout') { // for display purposes
            steps {
                checkout(
                    [
                        $class: 'GitSCM',
                        branches: [
                            [name: 'refs/heads/testing/hikey960_v2.5']
                        ],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [
                            [
                                $class: 'RelativeTargetDirectory',
                                relativeTargetDir: 'edk2'
                            ],
                            [
                                $class: 'CleanCheckout'
                            ],
                            [
                                $class: 'CloneOption',
                                depth: 0,
                                noTags: false,
                                reference: '',
                                shallow: true
                            ]
                        ],
                        submoduleCfg: [],
                        userRemoteConfigs: [
                            [url: 'https://github.com/96boards-hikey/edk2.git']
                        ]
                    ]
                )
                checkout(
                    [
                        $class: 'GitSCM',
                        branches: [[name: 'refs/heads/integration']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [
                            [
                                $class: 'RelativeTargetDirectory',
                                relativeTargetDir: 'arm-trusted-firmware'
                            ],
                            [
                                $class: 'CleanCheckout'
                            ],
                            [
                                $class: 'CloneOption',
                                noTags: false,
                                reference: '',
                                shallow: true
                            ]
                        ],
                        submoduleCfg: [],
                        userRemoteConfigs: [
                            [url: 'https://github.com/ARM-software/arm-trusted-firmware.git']
                        ]
                    ]
                )
                checkout(
                    [
                        $class: 'GitSCM',
                        branches: [[name: 'refs/heads/testing/hikey960_v1.3.4']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [
                            [
                                $class: 'RelativeTargetDirectory',
                                relativeTargetDir: 'OpenPlatformPkg'
                            ],
                            [
                                $class: 'CleanCheckout'
                            ],
                            [
                                $class: 'CloneOption',
                                noTags: false,
                                reference: '',
                                shallow: true
                            ]
                        ],
                        submoduleCfg: [],
                        userRemoteConfigs: [
                            [url: 'https://github.com/96boards-hikey/OpenPlatformPkg.git']
                        ]
                    ]
                )
                checkout(
                    [
                        $class: 'GitSCM',
                        branches: [[name: 'refs/heads/master']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [
                            [
                                $class: 'RelativeTargetDirectory',
                                relativeTargetDir: 'uefi-tools'
                            ],
                            [
                                $class: 'CleanCheckout'
                            ],
                            [
                                $class: 'CloneOption',
                                noTags: false,
                                reference: '',
                                shallow: true
                            ]
                        ],
                        submoduleCfg: [],
                        userRemoteConfigs: [
                            [url: 'https://github.com/96boards-hikey/uefi-tools.git']
                        ]
                    ]
                )
                checkout(
                    [
                        $class: 'GitSCM',
                        branches: [[name: 'refs/heads/master']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [
                            [
                                $class: 'RelativeTargetDirectory',
                                relativeTargetDir: 'atf-fastboot'
                            ],
                            [
                                $class: 'CleanCheckout'
                            ],
                            [
                                $class: 'CloneOption',
                                noTags: false,
                                reference: '',
                                shallow: true
                            ]
                        ],
                        submoduleCfg: [],
                        userRemoteConfigs: [
                            [url: 'https://github.com/96boards-hikey/atf-fastboot.git']
                        ]
                    ]
                )
                checkout(
                    [
                        $class: 'GitSCM',
                        branches: [[name: 'refs/heads/master']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [
                            [
                                $class: 'RelativeTargetDirectory',
                                relativeTargetDir: 'optee_os'
                            ],
                            [
                                $class: 'CleanCheckout'
                            ],
                            [
                                $class: 'CloneOption',
                                noTags: false,
                                reference: '',
                                shallow: true
                            ]
                        ],
                        submoduleCfg: [],
                        userRemoteConfigs: [
                            [url: 'https://github.com/OP-TEE/optee_os.git']
                        ]
                    ]
                )
                checkout(
                    [
                        $class: 'GitSCM',
                        branches: [[name: 'refs/heads/testing/hikey960_v1.2']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [
                            [
                                $class: 'RelativeTargetDirectory',
                                relativeTargetDir: 'l-loader'
                            ],
                            [
                                $class: 'CleanCheckout'
                            ],
                            [
                                $class: 'CloneOption',
                                noTags: false,
                                reference: '',
                                shallow: true
                            ]
                        ],
                        submoduleCfg: [],
                        userRemoteConfigs: [
                            [url: 'https://github.com/96boards-hikey/l-loader.git']
                        ]
                    ]
                )
            }
        }
        stage('Build EDK2') { // for display purposes
            steps {
                withEnv(["PATH+mytool=:/sbin", "WORKSPACE=",
                    "GENERATE_PTABLE=1",
                    "BUILD_CC=/usr/bin/gcc-5", "BUILD_CXX=/usr/bin/g++-5"]) {
                        sh  '''
                            cd edk2 && ln -s ../OpenPlatformPkg && cd -
                            bash l-loader/build_uefi.sh  hikey
                            '''
                }
            }
        }
        stage('Generate ptable') {
            steps {
                withEnv(["PATH+mytool=:/sbin", "WORKSPACE="]) {
                    dir("l-loader") {
                        sh  '''
                            PTABLE=linux-8g SECTOR_SIZE=512 bash -x generate_ptable.sh
                            cp prm_ptable.img linux-8g.img
                            PTABLE=aosp-8g SECTOR_SIZE=512 bash -x generate_ptable.sh
                            cp prm_ptable.img aosp-8g.img
                            '''
                    }
                }
            }
        }

        stage('Archive artifacts') {
            steps {
                dir("l-loader") {
                    archiveArtifacts artifacts: 'fip.bin, l-loader.bin, recovery.bin, fastboot.bin, linux-8g.img, aosp-8g.img', onlyIfSuccessful: true
                }
            }
        }
    }
}